### ISSUE TITLE
SQLITE_DBCONFIG_DEFENSIVE setting, SQLCipher migration, and other major updates wanted

### ISSUE THREAD

**Issue by brody2consult** [brodysoft/Cordova-sqlcipher-adaptor#80]
* [x] ~~Recent SQLCipher 4 update - SQLCipher 4.0.1 which *does* include the SQLite 3.26.0 security update (#79)~~
* [x] `SQLITE_DBCONFIG_DEFENSIVE` setting to defend against a potential data loss issue, due to malicious SQL statements (possible security vulnerability), which should be considered a possibly breaking change ref:
  - litehelpers/Cordova-sqlite-storage#838
  - <https://www.sqlite.org/security.html>
  - <https://www.sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigdefensive>
* [ ] SQLCipher version migration (#83)
* [ ] Other major updates from litehelpers/Cordova-sqlite-storage#773

ADDITIONAL reference links:
* <https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/>
* <https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283>

**Comment by stormtek** [comment]
Does this mean an update for SQLCipher is incoming that includes SQLCipher 4.0.1?

**Comment by brody2consult** [comment]
> Does this mean an update for SQLCipher is incoming that includes SQLCipher 4.0.1?

I hope to make the update soon.

**Comment by brody2consult** [comment]
This plugin is now updated with SQLCipher 4.0.1. I am keeping this issue open, with updated title, due to some other items that are still wanted (see description).

I still cannot promise when I will get a chance to do the other items due to other commitments and priorities. This plugin is no longer under active development (see #81). Commercial support for priority feature development is available, please contact <sales@litehelpers.net> for more information.
